"use client";

import { ArrowRight, FileCheck2 } from "lucide-react";
import { motion } from "framer-motion";
import { BrandButton } from "@/components/ui/brand-button";
import { CanvasText } from "@/components/ui/canvas-text";

/** Three dark-green shades for the "AI way" canvas-text accent — calm, on-brand, no shimmer. */
const AI_WAY_COLORS = [
  "rgba(3, 98, 76, 1)",
  "rgba(2, 74, 57, 1)",
  "rgba(4, 56, 43, 1)",
];

/**
 * "One message → finished artifact" proof visual.
 * A small trigger message produces a real, readable document — the document
 * (not the chat) is the centrepiece. Distinct from the Home AIOS-teaser,
 * which shows the chat thread + a file chip; here the artifact itself is
 * the focal object, in a tight, crisp frame (AIOS register).
 */
function ArtifactPanel() {
  return (
    <div className="mx-auto w-full max-w-[420px] md:mx-0 md:ml-auto">
      {/* Trigger — one small team-message bubble, the spark */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.6 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="mb-4 flex justify-end"
      >
        <div
          className="max-w-[78%] px-4 py-2.5 text-fg shadow-sm"
          style={{
            background: "#ffffff",
            borderRadius: "14px 14px 4px 14px",
            fontSize: "var(--text-small)",
            border: "1px solid var(--border)",
          }}
        >
          Draft the offer letter for our new hire.
        </div>
      </motion.div>

      {/* Artifact — the finished document, large and real */}
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 16 }}
        whileInView={{ opacity: 1, scale: 1, y: 0 }}
        viewport={{ once: true, amount: 0.4 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="overflow-hidden rounded-[16px] bg-white"
        style={{ boxShadow: "var(--shadow-card)", border: "1px solid var(--border)" }}
      >
        {/* Letterhead */}
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div>
            <p className="font-display font-bold text-fg" style={{ fontSize: "var(--text-small)" }}>
              Al Noor Trading
            </p>
            <p className="text-fg-3" style={{ fontSize: "0.7rem" }}>
              Dubai, UAE
            </p>
          </div>
          <span
            className="rounded-full px-3 py-1 font-semibold"
            style={{
              fontSize: "0.68rem",
              color: "var(--elyst-emerald)",
              background: "var(--green-tint-07)",
            }}
          >
            Offer Letter
          </span>
        </div>

        {/* Body — greeked lines, legible enough to read the opening */}
        <div className="flex flex-col gap-3 px-6 py-6">
          <p className="text-fg-2" style={{ fontSize: "var(--text-small)", lineHeight: 1.6 }}>
            Dear Rahul Iyer,
            <br />
            We are pleased to confirm your appointment as{" "}
            <span className="font-semibold text-fg">Operations Executive</span>, reporting
            to the Operations Manager, with effect from 1 July 2026.
          </p>
          <div className="mt-1 flex flex-col gap-2">
            <span className="h-2 w-[92%] rounded-full" style={{ background: "var(--surface-muted)" }} />
            <span className="h-2 w-[78%] rounded-full" style={{ background: "var(--surface-muted)" }} />
            <span className="h-2 w-[85%] rounded-full" style={{ background: "var(--surface-muted)" }} />
            <span className="h-2 w-[60%] rounded-full" style={{ background: "var(--surface-muted)" }} />
          </div>
        </div>

        {/* Generated-by marker */}
        <div className="flex items-center gap-2 border-t border-border px-6 py-3.5">
          <FileCheck2 className="h-4 w-4 text-emerald" />
          <span className="font-semibold text-emerald" style={{ fontSize: "0.78rem" }}>
            offer-letter-rahul-iyer.pdf
          </span>
          <span className="ml-auto text-fg-3" style={{ fontSize: "0.7rem" }}>
            Generated by AIOS · 09:42
          </span>
        </div>
      </motion.div>
    </div>
  );
}

export default function AiosHero() {
  return (
    <section
      className="bg-bg"
      style={{ padding: "clamp(40px, 5vw, 72px) var(--section-px)" }}
    >
      <div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-[9fr_11fr]">
        {/* Left — copy */}
        <div>
          <span className="chip">AIOS for Business</span>
          <h1
            className="mt-6 text-fg"
            style={{ fontSize: "var(--text-h1)", lineHeight: 1.12 }}
          >
            It&rsquo;s time to work
            <br />
            the{" "}
            <CanvasText
              text="AI way"
              backgroundClassName="bg-emerald"
              colors={AI_WAY_COLORS}
              lineGap={4}
              animationDuration={16}
              curveIntensity={6}
            />
          </h1>
          <p
            className="mt-5 max-w-md text-fg-2"
            style={{ fontSize: "var(--text-body)" }}
          >
            Built for teams of 5–50 with no technical staff, across India and
            the GCC. Message it like a colleague — it answers, drafts, and
            acts.
          </p>

          <div className="mt-8">
            <BrandButton href="/contact" tone="green">
              Book a call
              <ArrowRight className="h-4 w-4" />
            </BrandButton>
          </div>
          <p className="mt-4 text-fg-3" style={{ fontSize: "var(--text-small)" }}>
            Your team learns nothing new — it already lives in WhatsApp.
          </p>
        </div>

        {/* Right — proof visual: one message → finished artifact */}
        <ArtifactPanel />
      </div>
    </section>
  );
}
